version: '3.9'
volumes:
  data-write:
  data-read:
services:
  db-write:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: plexus
      MYSQL_DATABASE: book_swap
      MYSQL_USER: plexus
      MYSQL_PASSWORD: plexus
    volumes:
      - data-write:/var/lib/mysql
    ports:
      - "3306:3306"
  db-read:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=book_swap_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - data-read:/data/db
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
    links:
      - db-read
    restart: unless-stopped
    ports:
      - "8081:8081"
  book_swap:
    image: target-image:latest
    ports:
      - "8080:8080"
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
      image: bitnami/kafka:latest
      container_name: kafka
      hostname: kafka
      restart: always
      ports:
        - '9094:9094'
      environment:
        - KAFKA_CFG_NODE_ID=1
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_CFG_BROKER_ID=1
        - KAFKA_CFG_PROCESS_ROLES=broker,controller
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@:9093
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper