spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/book_swap
    username: root
    password: plexus
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book_swap_mongo
      username: root
      password: password
      authentication-database: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    template:
      default-topic: book-swap
    bootstrap-servers: localhost:9094
    producer:
      bootstrap-servers: localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer